---
-  hosts: switch1

   tasks:
     - name: VLAN configuration
       arubaoscx_vlan:
         vlan_id: "{{ item.vlan_id }}"
         state: "{{ item.state }}"
       with_items:
         - { vlan_id: 2, state: 'absent' }
         - { vlan_id: 3, state: 'absent' }
         - { vlan_id: 4, state: 'absent' }

     - name: Layer2 Interface configuration
       arubaoscx_l2_interface:
         interface: "{{ item.interface }}"
         state: "{{ item.state }}"
       with_items:
         - { interface: 1/1/2, state: 'absent' }
         - { interface: 1/1/3, state: 'absent' }

     - name: Layer3 Interface configuration
       arubaoscx_l3_interface:
         interface: "{{ item.interface }}"
         state: "{{ item.state }}"
       with_items:
         - { interface: 1/1/4, state: 'absent' }

     - name: VLAN Interface configuration
       arubaoscx_vlan_interface:
         interface: "{{ item.interface }}"
         state: "{{ item.state }}"
       with_items:
         - { interface: vlan2, state: 'absent' }

